### ISSUE TITLE
Segfault on large dataset

### ISSUE THREAD

**Issue by RyanMarcus** [gvinciguerra/PGM-index#6]
Hello!

We encountered a segfault when training a `PGMIndex<uint64_t, 16, 4>` on a larger (800M keys) dataset: https://www.dropbox.com/s/j1d4ufn4fyb4po2/osm_cellids_800M_uint64.zst

Unfortunately, the trace isn't super useful:
```
#0  0x00007f5af123727e in clock_nanosleep@GLIBC_2.2.5 () from /usr/lib/libc.so.6
#1  0x00007f5af123cbf7 in nanosleep () from /usr/lib/libc.so.6
#2  0x00007f5af123cb2e in sleep () from /usr/lib/libc.so.6
#3  0x00007f5af16b26ca in debug_wait_gdb () at lib.c:268
#4  <signal handler called>
#5  0x000055eec8226950 in unsigned long make_segmentation<PGMIndex<unsigned long, 16ul, 4ul, double>::PGMIndex<__gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > > >(__gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > >, __gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > >)::{lambda(auto:1)#3}, PGMIndex<unsigned long, 16ul, 4ul, double>::PGMIndex<__gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > > >(__gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > >, __gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > >)::{lambda(auto:1, auto:2, auto:3)#2}>(unsigned long, unsigned long, PGMIndex<unsigned long, 16ul, 4ul, double>::PGMIndex<__gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > > >(__gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > >, __gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > >)::{lambda(auto:1)#3}, PGMIndex<unsigned long, 16ul, 4ul, double>::PGMIndex<__gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > > >(__gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > >, __gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > >)::{lambda(auto:1)#3}) ()
#6  0x000055eec8226ffc in PGMIndex<unsigned long, 16ul, 4ul, double>::PGMIndex<__gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > > >(__gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > >, __gnu_cxx::__normal_iterator<unsigned long const*, std::vector<unsigned long, std::allocator<unsigned long> > >) ()
#7  0x000055eec822744f in std::_Function_handler<void (), sosd::Benchmark<unsigned long>::Run<PGM<unsigned long, 16> >()::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#8  0x000055eec81eae5e in util::timing(std::function<void ()>) ()
```

Thanks,
Ryan

**Comment by RyanMarcus** [comment]
Confirmed fixed! Thanks! 🎉🎉🎉
